// Generated by CoffeeScript 1.3.3
(function() {

  define(['app/module/models/lottoPeli'], function(LottoPeli) {
    return Backbone.Collection.extend({
      model: LottoPeli,
      initialize: function() {
        return this;
      }
    });
  });

}).call(this);
